### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [haniokasai/KeepInventory#1]
I put sln to plugins folder and i get

>  WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly MiNET, Version=1.0.1174.0, Culture=neutral, PublicKeyToken=null as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a as a plugin.
 WARN [?] - Failed loading exported types for assembly MiNET, Version=1.0.1174.0, Culture=neutral, PublicKeyToken=null as a plugin.
when i start server

**Comment by haniokasai** [comment]
I have NOT FINISHED this plugin.
if you built this plugin correctly,still you cant keep your inventory.
